"""
clear_data.py

Clears all intermediate data folders generated by the pipeline:
    - downloaded_images/
    - background_filtered/
    - embedded_vectors/
    - csv/

Usage:
    python clear_data.py
"""

import os
import shutil
from pathlib import Path

# ---------------------------------------------------------------------------
# CONFIG SETUP
# ---------------------------------------------------------------------------

DATA_DIRS = [
    "../data/downloaded_images",
    "../data/background_filtered",
    "../data/embedded_vectors",
    "../data/csv",
]

# ---------------------------------------------------------------------------
# CORE LOGIC
# ---------------------------------------------------------------------------

def clear_dir(dir_path: str) -> None:
    """
    Deletes all files inside a directory without deleting the directory itself.

    Args:
        dir_path: Path to the directory to clear.
    """
    path = Path(dir_path)

    if not path.exists():
        print(f"  [skipped]  {dir_path} does not exist.")
        return

    for item in path.iterdir():
        # Skip .gitkeep so the folder stays tracked in git.
        if item.name == ".gitkeep":
            continue
        if item.is_file():
            item.unlink()
        elif item.is_dir():
            shutil.rmtree(item)

    print(f"  [cleared]  {dir_path}")


# ---------------------------------------------------------------------------
# ENTRY POINT
# ---------------------------------------------------------------------------

def main():
    print("Clearing data folders...")
    for dir_path in DATA_DIRS:
        clear_dir(dir_path)
    print("\n Clear_data.py finished.\n")


if __name__ == "__main__":
    main()